### ISSUE TITLE
[faces]Optional DateTimeAPIの型が使えるようにする

### ISSUE THREAD

**Issue by master-of-sugar** [reels-project/reels#5]
jsf converterを作る。JPAのようにdefault converterのような仕組みがあればいいのに。

**Comment by master-of-sugar** [comment]
Optionalはjavax.faces.convertで提供されるもの全て対応する必要がある。
なにか良い方法ないかなあ。

**Comment by shohei-nozaki** [comment]
Primefacesは全Converter継承して作りなおしてましたｗ

**Comment by master-of-sugar** [comment]
そうなっちゃいます？

**Comment by master-of-sugar** [comment]
```
<f:xxxConverter optional="true" />
```

こんな感じがいいかな？

**Comment by master-of-sugar** [comment]
標準を置き換えるパターンと、別で作るパターンどっちがいいんだろ？？

```
<reels:xxxConverter optional="true" />
```

のように名前は同じだけど別物として扱ったほうがいい？？
